# Copyright 2026 TAHAI Web Services
# SPDX-License-Identifier: Apache-2.0
"""Verify actual packaged resource bytes, including generated third-party credits."""

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

SOURCE = Path(__file__).resolve().parents[4]
sys.path.insert(0, str(SOURCE / 'tools/grit'))
from grit.format import data_pack


def resource_id(header, symbol):
    matches = re.findall(r'^#define ' + re.escape(symbol) + r' (\d+)$',
                         header.read_text(), re.MULTILINE)
    if len(matches) != 1:
        raise ValueError(f'Missing or ambiguous generated resource ID: {symbol}')
    return int(matches[0])


def validate_credits(credits):
    text = credits.decode('utf-8')
    required = ('Generated by licenses.py', 'https://crates.io/crates/adblock',
                'EasyList and EasyPrivacy declarative filter data',
                'Mozilla Public License', 'Attribution-ShareAlike')
    if 'This is sample credits page' in text or any(s not in text for s in required):
        raise ValueError('Release credits are sample/incomplete; regenerate the real third-party notices')


def unpack_credits(blob, build):
    if not blob.startswith(b'\x1e\x9b') or len(blob) < 9:
        raise ValueError('Expected Chromium Brotli-compressed credits resource')
    expected_size = int.from_bytes(blob[2:8], 'little')
    if not 0 < expected_size <= 32 * 1024 * 1024:
        raise ValueError('Invalid credits resource size')
    result = subprocess.run([str(build / 'brotli.exe'), '-d', '-c'],
                            input=blob[8:], capture_output=True, check=True,
                            timeout=60)
    if len(result.stdout) != expected_size:
        raise ValueError('Credits decompressed size mismatch')
    return result.stdout


def verify(build):
    build = build.resolve(strict=True)
    resources = data_pack.ReadDataPack(str(build / 'resources.pak')).resources
    credits_id = resource_id(build / 'gen/components/grit/components_resources.h',
                             'IDR_ABOUT_UI_CREDITS_HTML')
    credits = unpack_credits(resources[credits_id], build)
    validate_credits(credits)
    if credits != (build / 'gen/components/resources/about_credits.html').read_bytes():
        raise ValueError('Packaged credits differ from generated credits')
    checks = {'credits': hashlib.sha256(credits).hexdigest()}
    header = build / 'gen/chrome/grit/browser_resources.h'
    for symbol, relative in (
            ('IDR_TAHAI_GUARD_EASYLIST', 'third_party/tahai_guard_lists/easylist-network.txt'),
            ('IDR_TAHAI_GUARD_EASYPRIVACY', 'third_party/tahai_guard_lists/easyprivacy-network.txt'),
            ('IDR_TAHAI_SKIN_CREATOR_KIT', 'docs/tahai-skins/skin-creator-kit.zip')):
        expected = (SOURCE / relative).read_bytes()
        if resources[resource_id(header, symbol)] != expected:
            raise ValueError(f'Packaged resource differs from release source: {symbol}')
        checks[symbol] = hashlib.sha256(expected).hexdigest()
    return checks


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--build-dir', type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(verify(args.build_dir), indent=2))
