// Copyright 2026 TAHAI Web Services
// SPDX-License-Identifier: Apache-2.0

#ifndef CHROME_BROWSER_UI_WEBUI_TAHAI_TAHAI_MISSION_SERVICE_H_
#define CHROME_BROWSER_UI_WEBUI_TAHAI_TAHAI_MISSION_SERVICE_H_

#include <cstddef>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

#include "base/memory/raw_ptr.h"
#include "base/no_destructor.h"
#include "chrome/browser/profiles/profile_keyed_service_factory.h"
#include "chrome/browser/ui/webui/tahai/tahai_oi_link_contract.h"
#include "components/keyed_service/core/keyed_service.h"

class PrefService;
class Profile;

namespace tahai {

struct TahaiMissionCapsuleImport;

struct MissionStep {
  std::string label;
  bool complete = false;
};

struct MissionEvent {
  // A fixed vocabulary that drives the locally rendered Timeline filters. It
  // never contains a URL, page title, payload, or other browsing data.
  std::string kind;
  std::string detail;
  std::string created_at;
  // Every generated event is locally chained to its immediately preceding
  // event. The browser never places page contents or credentials in either
  // input to this digest.
  std::string previous_hash;
  std::string entry_hash;
};

struct MissionEvidence {
  // Evidence markers deliberately describe only the operator action, never
  // the current page, its title, its URL, a screenshot, or page data.
  std::string label;
  std::string capture_scope;
  std::string captured_at;
};

struct MissionSummary {
  std::string id;
  std::string title;
  std::string type;
  std::string created_at;
  std::string updated_at;
  std::vector<MissionStep> steps;
  std::vector<MissionStep> validation_steps;
  std::vector<MissionStep> rollback_steps;
  bool escalation_required = false;
  std::string export_profile;
  std::vector<MissionEvidence> evidence;
  std::vector<MissionEvent> timeline;
  // Future hosted handoff metadata remains inert in the browser. This is a
  // validated opaque record only; it cannot carry a tenant, auth material,
  // browsing data, raw content, or an arbitrary remote destination.
  std::optional<TahaiOiLink> oi_link;
  // Legacy timeline records are migrated into a local chain, but are never
  // represented as cryptographically verified historical evidence.
  bool timeline_integrity_verified = true;
  // Archived missions are retained as immutable local records. They may be
  // restored or used as the source for a fresh generated runbook, but their
  // checkpoint, evidence, escalation, and export state cannot be changed.
  bool archived = false;
};

// Owns non-secret Mission metadata for exactly one Chromium Profile. Passwords,
// cookies, tokens, page content, headers, screenshots, and authentication state
// are never part of this service's schema. Runbook labels and timeline entries
// are generated by the browser; no page data or arbitrary operator notes enter
// this service.
class MissionService : public KeyedService {
 public:
  explicit MissionService(Profile* profile);
  MissionService(const MissionService&) = delete;
  MissionService& operator=(const MissionService&) = delete;
  ~MissionService() override;

  const std::vector<MissionSummary>& missions() const { return missions_; }
  std::optional<MissionSummary> CreateMission(std::string_view title,
                                              std::string_view type);
  // Creates a fresh local Mission from a previously authenticated capsule.
  // Source identity, title, timestamps, and event ledger are never restored.
  std::optional<MissionSummary> ImportSanitizedMissionCapsule(
      const TahaiMissionCapsuleImport& capsule);
  bool ToggleStep(std::string_view mission_id, size_t step_index);
  bool ToggleValidationStep(std::string_view mission_id, size_t step_index);
  bool ToggleRollbackStep(std::string_view mission_id, size_t step_index);
  bool ToggleEscalation(std::string_view mission_id);
  bool AddEvidenceMarker(std::string_view mission_id);
  bool SetExportProfile(std::string_view mission_id,
                        std::string_view export_profile);
  bool ArchiveMission(std::string_view mission_id);
  bool RestoreMission(std::string_view mission_id);
  std::optional<MissionSummary> DuplicateMission(std::string_view mission_id);
  bool DeleteMission(std::string_view mission_id);
  bool persistence_enabled() const;

 private:
  MissionSummary* FindMission(std::string_view mission_id);
  void Load();
  void Save();

  const raw_ptr<Profile> profile_;
  const raw_ptr<PrefService> prefs_;
  std::vector<MissionSummary> missions_;
};

class MissionServiceFactory : public ProfileKeyedServiceFactory {
 public:
  static MissionService* GetForProfile(Profile* profile);
  static MissionServiceFactory* GetInstance();

  MissionServiceFactory(const MissionServiceFactory&) = delete;
  MissionServiceFactory& operator=(const MissionServiceFactory&) = delete;

 private:
  friend base::NoDestructor<MissionServiceFactory>;

  MissionServiceFactory();
  ~MissionServiceFactory() override;

  std::unique_ptr<KeyedService> BuildServiceInstanceForBrowserContext(
      content::BrowserContext* context) const override;
};

}  // namespace tahai

#endif  // CHROME_BROWSER_UI_WEBUI_TAHAI_TAHAI_MISSION_SERVICE_H_
