// Copyright 2026 TAHAI Web Services
// SPDX-License-Identifier: Apache-2.0

#ifndef CHROME_BROWSER_UI_TAHAI_TAHAI_SKIN_MANAGER_H_
#define CHROME_BROWSER_UI_TAHAI_TAHAI_SKIN_MANAGER_H_

#include "ui/base/interaction/element_identifier.h"

class BrowserWindowInterface;

namespace tahai::skins {
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerImportElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerInstallElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerPreviewElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerReviewElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerTrustReviewElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerRevisionReviewElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerRevisionDiffElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerRevisionAckElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerPublishersElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerPublisherKeyIdElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerPublisherKeyElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerPublisherReviewKeyElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerPublisherRevokeElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerApplyElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerApplyWindowElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerResetElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerActivateModeElementId);
DECLARE_ELEMENT_IDENTIFIER_VALUE(kSkinManagerActivateCustomModeElementId);
bool CanShowSkinManager(BrowserWindowInterface* browser);
void ShowSkinManager(BrowserWindowInterface* browser);
}  // namespace tahai::skins

#endif  // CHROME_BROWSER_UI_TAHAI_TAHAI_SKIN_MANAGER_H_
