#!/usr/bin/env python3
"""Reproduce the bundled offline creator kit without downloading anything."""
import argparse
import base64
import io
import json
from pathlib import Path
import zipfile

ROOT = Path(__file__).resolve().parent


def outputs():
    from build_skin import build
    starter = ROOT / "starter-skin"
    archive = build(starter)
    data = {"manifest": json.loads((starter / "manifest.json").read_text()),
            "png": base64.b64encode((starter / "assets/preview.png").read_bytes()).decode()}
    script = ("// Generated by build_creator_kit.py.\nwindow.tahaiStarter = " +
              json.dumps(data, separators=(",", ":")) + ";\n").encode()
    entries = {"studio-default.js": script, "starter-skin.tahaiskin": archive}
    for name in ("studio.html", "studio.css", "studio.js", "build_skin.py",
                 "SKIN_AUTHORING.md"):
        entries[name] = (ROOT / name).read_bytes()
    for path in sorted(starter.rglob("*")):
        if path.is_file():
            entries["starter-skin/" + path.relative_to(starter).as_posix()] = path.read_bytes()
    entries["README.md"] = (starter / "README.md").read_bytes()
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_STORED) as result:
        for name, content in sorted(entries.items()):
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.create_system = 0
            result.writestr(info, content)
    return {"studio-default.js": script, "starter-skin.tahaiskin": archive,
            "skin-creator-kit.zip": stream.getvalue()}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in outputs().items():
        target = ROOT / name
        if args.check:
            if not target.exists() or target.read_bytes() != content:
                raise SystemExit(f"Stale creator output: {name}")
        else:
            target.write_bytes(content)
        print(f"{'Checked' if args.check else 'Built'} {name}: {len(content)} bytes")
