#!/usr/bin/env python3
"""Reproduce the bundled offline creator kit without downloading anything."""
import argparse
import base64
import io
import json
from pathlib import Path
import re
import tempfile
import zipfile

from operational_templates import TEMPLATES, readme, source_manifest

ROOT = Path(__file__).resolve().parent


def validate_compatibility(version_file):
    """Release-only guard; the exported standalone kit needs no source checkout.

    Never rewrite an author's ranges here. A new engine needs an explicit
    template review and regenerated archives, not silent range widening.
    """
    values = re.findall(r"^MAJOR=(\d+)$", Path(version_file).read_text().strip(), re.M)
    if len(values) != 1 or not 1 <= int(values[0]) <= 999:
        raise ValueError("Expected one valid MAJOR in the selected chrome/VERSION")
    major = int(values[0])
    expected = {"min_chromium_major": major, "max_chromium_major": major}
    for name in ("starter-skin/manifest.json", "operational-starter-skin/manifest.json",
                 "operational-skin-v2.example.json"):
        manifest = json.loads((ROOT / name).read_text(encoding="utf-8"))
        if manifest.get("compatibility") != expected:
            raise ValueError(f"Bundled {name} must explicitly target Chromium {major}; "
                             "review the template and regenerate the creator kit")


def outputs(chromium_version_file=None):
    if chromium_version_file is not None:
        validate_compatibility(chromium_version_file)
    from build_skin import build
    starter = ROOT / "starter-skin"
    operational_starter = ROOT / "operational-starter-skin"
    archive = build(starter)
    operational_archive = build(operational_starter)
    data = {"manifest": json.loads((starter / "manifest.json").read_text()),
            "png": base64.b64encode((starter / "assets/preview.png").read_bytes()).decode()}
    script = ("// Generated by build_creator_kit.py.\nwindow.tahaiStarter = " +
              json.dumps(data, separators=(",", ":")) + ";\n").encode()
    entries = {
        "studio-default.js": script,
        "starter-skin.tahaiskin": archive,
        "operational-starter-skin.tahaiskin": operational_archive,
        "OPERATIONAL_SKIN_V2.md": (ROOT / "OPERATIONAL_SKIN_V2.md").read_bytes(),
        "operational-skin-v2.example.json":
            (ROOT / "operational-skin-v2.example.json").read_bytes(),
    }
    for name in ("studio.html", "studio.css", "studio.js", "build_skin.py",
                 "build_creator_kit.py", "SKIN_AUTHORING.md"):
        entries[name] = (ROOT / name).read_bytes()
    for path in sorted(starter.rglob("*")):
        if path.is_file():
            entries["starter-skin/" + path.relative_to(starter).as_posix()] = path.read_bytes()
    for path in sorted(operational_starter.rglob("*")):
        if path.is_file():
            entries["operational-starter-skin/" + path.relative_to(operational_starter).as_posix()] = path.read_bytes()
    preview = (operational_starter / "assets/preview.png").read_bytes()
    with tempfile.TemporaryDirectory(prefix="tahai-creator-templates-") as directory:
        for name in sorted(TEMPLATES):
            source = Path(directory) / name
            (source / "assets").mkdir(parents=True)
            manifest = (json.dumps(source_manifest(name), indent=2) + "\n").encode("utf-8")
            (source / "manifest.json").write_bytes(manifest)
            (source / "assets/preview.png").write_bytes(preview)
            entries[f"templates/{name}/manifest.json"] = manifest
            entries[f"templates/{name}/assets/preview.png"] = preview
            entries[f"templates/{name}/README.md"] = readme(name)
            entries[f"templates/{name}.tahaiskin"] = build(source)
    entries["operational_templates.py"] = (ROOT / "operational_templates.py").read_bytes()
    entries["README.md"] = (starter / "README.md").read_bytes()
    stream = io.BytesIO()
    with zipfile.ZipFile(stream, "w", compression=zipfile.ZIP_STORED) as result:
        for name, content in sorted(entries.items()):
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.create_system = 0
            result.writestr(info, content)
    return {"studio-default.js": script, "starter-skin.tahaiskin": archive,
            "operational-starter-skin.tahaiskin": operational_archive,
            "skin-creator-kit.zip": stream.getvalue()}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--chromium-version-file", type=Path,
                        help="Release guard against stale bundled compatibility ranges")
    args = parser.parse_args()
    for name, content in outputs(args.chromium_version_file).items():
        target = ROOT / name
        if args.check:
            if not target.exists() or target.read_bytes() != content:
                raise SystemExit(f"Stale creator output: {name}")
        else:
            target.write_bytes(content)
        print(f"{'Checked' if args.check else 'Built'} {name}: {len(content)} bytes")
