// Copyright 2026 TAHAI Web Services
// SPDX-License-Identifier: Apache-2.0

#include "chrome/browser/tahai_skins/skin_color_supplier.h"

#include <algorithm>
#include <utility>

#include "base/strings/string_number_conversions.h"
#include "chrome/browser/ui/color/chrome_color_id.h"
#include "ui/color/color_id.h"
#include "ui/color/color_mixer.h"
#include "ui/color/color_provider.h"
#include "ui/color/color_recipe.h"
#include "ui/gfx/color_utils.h"

namespace tahai::skins {

SkinColorSupplier::SkinColorSupplier(TahaiSkinAppearance appearance,
                                     SkBitmap decoration)
    : CustomThemeSupplier(ThemeType::kAutogenerated),
      appearance_(std::move(appearance)),
      decoration_(std::move(decoration)) {}

SkinColorSupplier::~SkinColorSupplier() = default;

std::optional<SkColor> SkinColorSupplier::Color(
    std::string_view token,
    const ui::ColorProviderKey& key) const {
  // Respect the person's OS forced-color palette above package preferences.
  if (key.forced_colors != ui::ColorProviderKey::ForcedColors::kNone) {
    return std::nullopt;
  }
  const auto& colors =
      key.contrast_mode == ui::ColorProviderKey::ContrastMode::kHigh
          ? appearance_.high_contrast_tokens.colors
      : key.color_mode == ui::ColorProviderKey::ColorMode::kDark
          ? appearance_.dark_tokens.colors
          : appearance_.light_tokens.colors;
  const auto found = std::ranges::find_if(
      colors, [token](const auto& color) { return color.first == token; });
  uint32_t rgb = 0;
  if (found == colors.end() || found->second.size() != 7 ||
      !base::HexStringToUInt(std::string_view(found->second).substr(1), &rgb)) {
    return std::nullopt;
  }
  return SkColorSetRGB((rgb >> 16) & 0xff, (rgb >> 8) & 0xff, rgb & 0xff);
}

void SkinColorSupplier::AddColorMixers(ui::ColorProvider* provider,
                                       const ui::ColorProviderKey& key) const {
  const auto shell = Color("shell_background", key);
  if (!shell) {
    return;
  }
  auto& mixer = provider->AddMixer();
  const auto toolbar = *Color("toolbar_background", key);
  const auto text = *Color("toolbar_foreground", key);
  mixer[ui::kColorFrameActive] = {*shell};
  mixer[ui::kColorFrameInactive] = {*shell};
  mixer[kColorFrameCaptionActive] = {
      color_utils::GetColorWithMaxContrast(*shell)};
  mixer[kColorFrameCaptionInactive] = {kColorFrameCaptionActive};
  mixer[kColorToolbar] = {toolbar};
  mixer[kColorToolbarText] = {text};
  mixer[kColorToolbarButtonIcon] = {text};
  mixer[kColorToolbarButtonIconHovered] = {text};
  mixer[kColorToolbarButtonIconPressed] = {text};
  mixer[kColorToolbarButtonIconDisabled] = {SkColorSetA(text, 0x80)};
  mixer[kColorTabBackgroundActiveFrameActive] = {*Color("tab_background", key)};
  mixer[kColorTabBackgroundActiveFrameInactive] = {
      kColorTabBackgroundActiveFrameActive};
  mixer[kColorTabForegroundActiveFrameActive] = {*Color("tab_foreground", key)};
  mixer[kColorTabForegroundActiveFrameInactive] = {
      kColorTabForegroundActiveFrameActive};
  for (const auto id : {kColorTabBackgroundInactiveFrameActive,
                        kColorTabBackgroundInactiveFrameInactive,
                        kColorTabBackgroundInactiveHoverFrameActive,
                        kColorTabBackgroundInactiveHoverFrameInactive}) {
    mixer[id] = {*shell};
  }
  mixer[kColorTabForegroundInactiveFrameActive] = {
      color_utils::GetColorWithMaxContrast(*shell)};
  mixer[kColorTabForegroundInactiveFrameInactive] = {
      kColorTabForegroundInactiveFrameActive};
  mixer[kColorSidePanelCardBackground] = {*Color("panel_background", key)};
  mixer[kColorSidePanelCardPrimaryForeground] = {
      *Color("panel_foreground", key)};
  mixer[kColorSidePanelCardSecondaryForeground] = {
      kColorSidePanelCardPrimaryForeground};
  // Omnibox origins, security indicators, warnings, focus rings, permission
  // dialogs and web content retain Chromium's trusted color definitions.
}

}  // namespace tahai::skins
